In [2]:
import torch
print(torch.__version__)

2.7.0+cpu


# 1. Creating Tensor

In [2]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.rand(2,3)

tensor([[0.9740, 0.8420, 0.9388],
        [0.3289, 0.6088, 0.3277]])

In [7]:
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [8]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [10]:
torch.linspace(0,10 , 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [11]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
torch.full((3,2), 5)

tensor([[5, 5],
        [5, 5],
        [5, 5]])

In [13]:
torch.randint(size=(2,3), low=0, high=10)

tensor([[6, 7, 0],
        [4, 1, 4]])

# 2. Tensor Shape

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.5558, 0.2389, 0.3788],
        [0.4478, 0.2219, 0.9618]])

# 3. Tensor Datatype

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [23]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
x.dtype

torch.int64

In [25]:
# using dtype
torch.tensor(x, dtype=torch.float32)

C:\Users\Jehan\AppData\Local\Temp\ipykernel_15020\3199838035.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(x, dtype=torch.float32)


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [26]:
# (same)
torch.tensor([[1, 2, 3],[4, 5, 6]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [27]:
# to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# 4. Mathematical Operation
## i) Scaler 

In [30]:
x = torch.tensor([[.1,.2,.3],[.4,.5,.6]])

In [31]:
x + 2

tensor([[2.1000, 2.2000, 2.3000],
        [2.4000, 2.5000, 2.6000]])

In [33]:
x - 2

tensor([[-1.9000, -1.8000, -1.7000],
        [-1.6000, -1.5000, -1.4000]])

In [34]:
x * 3

tensor([[0.3000, 0.6000, 0.9000],
        [1.2000, 1.5000, 1.8000]])

In [35]:
x / 3

tensor([[0.0333, 0.0667, 0.1000],
        [0.1333, 0.1667, 0.2000]])

In [36]:
x // 3

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [37]:
x ** 2

tensor([[0.0100, 0.0400, 0.0900],
        [0.1600, 0.2500, 0.3600]])

In [38]:
x % 2

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

## ii) Element wise

In [46]:
x = torch.randint(size=(2,3), low=1, high=10)
y = torch.randint(size=(2,3), low=1, high=10)
x

tensor([[6, 5, 4],
        [2, 9, 7]])

In [47]:
y

tensor([[6, 6, 7],
        [1, 5, 2]])

In [48]:
x + y

tensor([[12, 11, 11],
        [ 3, 14,  9]])

In [49]:
x - y

tensor([[ 0, -1, -3],
        [ 1,  4,  5]])

In [50]:
x * y

tensor([[36, 30, 28],
        [ 2, 45, 14]])

In [51]:
x / y

tensor([[1.0000, 0.8333, 0.5714],
        [2.0000, 1.8000, 3.5000]])

In [52]:
x // y

tensor([[1, 0, 0],
        [2, 1, 3]])

In [53]:
x % y

tensor([[0, 5, 4],
        [0, 4, 1]])

In [54]:
x ** y

tensor([[46656, 15625, 16384],
        [    2, 59049,    49]])

## iii) Function

In [60]:
x = torch.linspace(-1,1, 5) * 10
x

tensor([-10.,  -5.,   0.,   5.,  10.])

In [61]:
torch.abs(x)

tensor([10.,  5.,  0.,  5., 10.])

In [62]:
torch.neg(x)

tensor([ 10.,   5.,  -0.,  -5., -10.])

In [64]:
x = torch.rand((2,3)) * 10
x

tensor([[9.7170, 5.4984, 0.8922],
        [7.1664, 2.5607, 7.8758]])

In [65]:
torch.round(x)

tensor([[10.,  5.,  1.],
        [ 7.,  3.,  8.]])

In [66]:
torch.ceil(x)

tensor([[10.,  6.,  1.],
        [ 8.,  3.,  8.]])

In [67]:
torch.floor(x)

tensor([[9., 5., 0.],
        [7., 2., 7.]])

In [68]:
torch.clamp(x, min=2,max=6)

tensor([[6.0000, 5.4984, 2.0000],
        [6.0000, 2.5607, 6.0000]])

## iv) Statistical Operation 

In [69]:
x

tensor([[9.7170, 5.4984, 0.8922],
        [7.1664, 2.5607, 7.8758]])

In [70]:
# sum
torch.sum(x)

tensor(33.7106)

In [73]:
torch.sum(x, dim=1)  # row wise

tensor([16.1076, 17.6030])

In [74]:
torch.sum(x, dim=0)  # col wise

tensor([16.8835,  8.0591,  8.7680])

In [75]:
# mean
torch.mean(x)

tensor(5.6184)

In [76]:
torch.mean(x)

tensor(5.6184)

In [77]:
torch.max(x)

tensor(9.7170)

In [78]:
torch.min(x)

tensor(0.8922)

In [79]:
torch.prod(x)

tensor(6889.5625)

In [80]:
torch.std(x)

tensor(3.3464)

In [81]:
torch.var(x)

tensor(11.1984)

In [82]:
torch.argmax(x)

tensor(0)

In [83]:
torch.argmin(x)

tensor(2)

# 5. Matrix Operation

In [96]:
x = torch.rand(2,3)
y = torch.rand(3,4)
x

tensor([[0.5052, 0.8010, 0.5158],
        [0.0089, 0.6844, 0.6587]])

In [93]:
torch.matmul(x,y)

tensor([[0.8560, 1.0552, 1.1855, 1.5297],
        [0.9939, 1.0987, 1.2657, 1.6877]])

In [94]:
a = torch.rand(3)
b = torch.rand(3)
b

tensor([0.6511, 0.4083, 0.3217])

In [95]:
torch.dot(a,b)

tensor(0.5553)

In [98]:
torch.transpose(x, 0,1)

tensor([[0.5052, 0.0089],
        [0.8010, 0.6844],
        [0.5158, 0.6587]])

In [101]:
z = torch.rand(3,3)
torch.det(z)

tensor(0.0356)

In [103]:
torch.inverse(z)

tensor([[-15.6554,   2.3303,  15.6954],
        [ 17.1080,  -2.5842, -15.5177],
        [  9.1947,  -0.2680,  -9.2894]])

# 6. Boolean Operation

In [106]:
x = torch.randint(size=(2,3), low=0, high=10)
y = torch.randint(size=(2,3), low=0, high=10)
x

tensor([[6, 4, 5],
        [5, 6, 7]])

In [107]:
y

tensor([[9, 9, 9],
        [6, 4, 6]])

In [108]:
x > y

tensor([[False, False, False],
        [False,  True,  True]])

In [109]:
x >= y

tensor([[False, False, False],
        [False,  True,  True]])

In [110]:
x < y

tensor([[ True,  True,  True],
        [ True, False, False]])

In [111]:
x <= y

tensor([[ True,  True,  True],
        [ True, False, False]])

In [112]:
x == y

tensor([[False, False, False],
        [False, False, False]])

In [113]:
x != y

tensor([[True, True, True],
        [True, True, True]])

# 7. Speacial Function

In [116]:
x = torch.rand(2,3)
x

tensor([[0.4852, 0.4592, 0.6640],
        [0.4279, 0.4506, 0.0947]])

In [117]:
torch.log(x)

tensor([[-0.7233, -0.7783, -0.4094],
        [-0.8488, -0.7971, -2.3566]])

In [118]:
torch.exp(x)

tensor([[1.6244, 1.5828, 1.9426],
        [1.5341, 1.5693, 1.0994]])

In [119]:
torch.sigmoid(x)

tensor([[0.6190, 0.6128, 0.6602],
        [0.6054, 0.6108, 0.5237]])

In [121]:
torch.softmax(x ,dim=0)

tensor([[0.5143, 0.5021, 0.6386],
        [0.4857, 0.4979, 0.3614]])

In [122]:
torch.softmax(x ,dim=1)

tensor([[0.3154, 0.3074, 0.3772],
        [0.3650, 0.3734, 0.2616]])

In [123]:
torch.relu(x)

tensor([[0.4852, 0.4592, 0.6640],
        [0.4279, 0.4506, 0.0947]])

# 8. Inplace Operation

In [126]:
x

tensor([[9.4852, 9.4592, 9.6640],
        [6.4279, 4.4506, 6.0947]])

In [127]:
y

tensor([[9, 9, 9],
        [6, 4, 6]])

In [125]:
x.add_(y)
x

tensor([[9.4852, 9.4592, 9.6640],
        [6.4279, 4.4506, 6.0947]])

In [130]:
x.relu_()

tensor([[0.9999, 0.9999, 0.9999],
        [0.9984, 0.9885, 0.9978]])

# 9. Copying a tensor

In [131]:
x

tensor([[0.9999, 0.9999, 0.9999],
        [0.9984, 0.9885, 0.9978]])

In [133]:
c = x.clone()
c

tensor([[0.9999, 0.9999, 0.9999],
        [0.9984, 0.9885, 0.9978]])

# 10. Operation on GPU

In [134]:
torch.cuda.is_available()

True

In [135]:
device = torch.device('cuda')
device

device(type='cuda')

In [136]:
torch.rand((2,3), device=device)

tensor([[0.3582, 0.6844, 0.6778],
        [0.6709, 0.2105, 0.8195]], device='cuda:0')

In [137]:
x

tensor([[0.9999, 0.9999, 0.9999],
        [0.9984, 0.9885, 0.9978]])

In [139]:
y = x.to(device)
y

tensor([[0.9999, 0.9999, 0.9999],
        [0.9984, 0.9885, 0.9978]], device='cuda:0')

# 11. Numpy and Pytorch

In [144]:
torch_arr = torch.rand(2,3)
torch_arr

tensor([[0.8894, 0.3071, 0.3521],
        [0.3467, 0.5416, 0.6123]])

In [143]:
import numpy as np
np_arr = np.random.rand(2,3)
np_arr

array([[0.52699269, 0.76062048, 0.51995173],
       [0.62477241, 0.55349575, 0.13484781]])

In [145]:
# torch -> numpy
torch_arr.numpy()

array([[0.8894295 , 0.3071428 , 0.35214978],
       [0.34665245, 0.5415726 , 0.6122645 ]], dtype=float32)

In [146]:
# numpy -> torch
torch.from_numpy(np_arr)

tensor([[0.5270, 0.7606, 0.5200],
        [0.6248, 0.5535, 0.1348]], dtype=torch.float64)

# 12. Reshape

In [147]:
x = torch.rand(4,4)
x

tensor([[0.8046, 0.3128, 0.0243, 0.1403],
        [0.3457, 0.4350, 0.9523, 0.1271],
        [0.9917, 0.6108, 0.2251, 0.2008],
        [0.6877, 0.8703, 0.1432, 0.2072]])

In [148]:
x.reshape(2,2,2,2)

tensor([[[[0.8046, 0.3128],
          [0.0243, 0.1403]],

         [[0.3457, 0.4350],
          [0.9523, 0.1271]]],


        [[[0.9917, 0.6108],
          [0.2251, 0.2008]],

         [[0.6877, 0.8703],
          [0.1432, 0.2072]]]])

In [149]:
x.flatten()

tensor([0.8046, 0.3128, 0.0243, 0.1403, 0.3457, 0.4350, 0.9523, 0.1271, 0.9917,
        0.6108, 0.2251, 0.2008, 0.6877, 0.8703, 0.1432, 0.2072])

In [150]:
x = torch.rand(1,2,4)
x.squeeze(0).shape

torch.Size([2, 4])

In [151]:
x = torch.rand(3,5)
x.unsqueeze(0).shape

torch.Size([1, 3, 5])