In [1]:
import torch

# y = x**2

In [2]:
x = torch.tensor(3.0, requires_grad=True)
x

tensor(3., requires_grad=True)

In [3]:
y = x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [4]:
y.backward()

In [5]:
x.grad

tensor(6.)

# y = x**2
# z = sin(y)

In [6]:
x = torch.tensor(5.47, requires_grad=True)
x

tensor(5.4700, requires_grad=True)

In [7]:
y = x**2
z = torch.sin(y)

In [8]:
z.backward()

In [9]:
x.grad

tensor(0.8281)

# y = x**2
# z = sin(y)
# u = e**z

In [10]:
x = torch.tensor(5.47, requires_grad=True)
y = x ** 2
z = torch.sin(y)
u = torch.exp(z)

In [11]:
u.backward()

In [12]:
x.grad

tensor(0.3055)

# Perceptron Backpropagation

In [13]:
x = torch.tensor(6.7)
y_true = torch.tensor(0.0)

In [14]:
w = torch.tensor(1.0 ,requires_grad=True)
b = torch.tensor(0.0 ,requires_grad=True)

In [15]:
z = torch.dot(x.unsqueeze(0),w.unsqueeze(0)) + b.unsqueeze(0)

In [16]:
y_pred = torch.sigmoid(z)

In [17]:
def binary_cross_entropy(y_true, y_pred):
    ephcilon = 1e-8
    y_pred = torch.clamp(y_pred, ephcilon , 1-ephcilon)
    return -(y_true * torch.log(y_pred)) + (1-y_true) * torch.log(1 - y_pred)

In [18]:
loss = binary_cross_entropy(y_true, y_pred)

In [19]:
loss.backward()

In [20]:
w.grad

tensor(-6.6918)

In [21]:
b.grad

tensor(-0.9988)

# Multivariate Function (partial Derivative)

In [22]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)

In [23]:
y = (x**2).mean()

In [24]:
y.backward()

In [25]:
print(x.grad)

tensor([0.6667, 1.3333, 2.0000])


# MLP

In [26]:
X = torch.tensor([3.9, 90])
y_true = torch.tensor(0.0)

In [27]:
W1 = torch.rand(2,2, requires_grad=True)
b1 = torch.rand(2, requires_grad=True)

In [28]:
z1 = torch.matmul(X, W1) + b1
z1

tensor([79.9966, 78.2017], grad_fn=<AddBackward0>)

In [29]:
o1 = torch.relu(z1)

In [30]:
W2 = torch.rand(2,1, requires_grad=True)
b2 = torch.rand(1, requires_grad=True)

In [31]:
z2 = torch.matmul(o1, W2) + b2

In [32]:
o2 = torch.sigmoid(z2)

In [33]:
o2

tensor([1.], grad_fn=<SigmoidBackward0>)

In [34]:
loss = binary_cross_entropy(y_true, o2)

In [35]:
loss.backward()

In [36]:
W1.grad

tensor([[nan, nan],
        [nan, nan]])

In [37]:
W2.grad

tensor([[nan],
        [nan]])

# Off Gradient Tracking

### way-1

In [39]:
x = torch.tensor(3.0, requires_grad=True)

In [42]:
with torch.no_grad():
    y = x**2

In [43]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### way-2

In [45]:
x = torch.tensor(3.0, requires_grad=True)

In [46]:
x.requires_grad_(False)

tensor(3.)

In [47]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

# way-3

In [48]:
x = torch.tensor(3.0, requires_grad=True)
y = x**2

In [49]:
z = y.detach()

In [50]:
y.backward()

In [51]:
z.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn